name: Build 4IFIR-configurator

on: 
  push:
  workflow_dispatch:

jobs:
  AIO-switch-updater:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git config --global --add safe.directory /__w/4IFIR-configurator/4IFIR-configurator
        git submodule update --init --recursive
        
    - name: Building aio-switch-updater
      run: |
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: 4IFIR-configurator
        path: 4IFIR-configurator.nro
